[net]
git-fetch-with-cli = true

[patch.crates-io]
google-youtube3 = { git = "https://github.com/OMGeeky/google-apis-rs.git", branch = "scope-derives-yt" }
google-apis-common = { git = "https://github.com/OMGeeky/google-apis-rs.git", branch = "scope-derives-yt" }
